#!/usr/bin/env bash

command="$1"

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "$TS_ROOT" ]; then
  TS_ROOT="$HOME/.ts"
fi
export TS_ROOT

if [ -z "$TS_DATA" ]; then
  TS_DATA="$HOME/.ts-data"
fi
export TS_DATA

export CURRENT_HOUR=$(date "+%H")
export CURRENT_MINUTE=$(date "+%M")
export CURRENT_DATE=$(date "+%m-%d-%Y")

bin_path="$(abs_dirname "$0")"
export PATH="$bin_path:$PATH"

case "$command" in
"" )
    ts-log
  ;;
* )
  command_path="$(command -v "ts-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "ts: no such command '$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
