#!/usr/bin/env bash

if [ ! -e "$TS_DATA/mail" ]; then
  echo 'ts: no mail configuration found'
  exit 1
else
  if [ ! -e "$TS_DATA/log-$CURRENT_DATE" ]; then
    echo 'ts: no log for today'
    exit 1
  else
    ts-show | mail -s "'Timesheet for $CURRENT_DATE'" "$(cat $TS_DATA/mail)"
  fi
fi
